travis:
  secure:
    BINSTAR_TOKEN: YQqTIk7iosTKE0Vwxn5x0DfIIJmGguXdufmBIaKUyJH9jspkP7hGkxtIfD91URPJvLWscKtvhjOXikc1otFsDhd+c06Micj7sFAZrKFXWbH6vkVILiEDORTR51iIorSe+dEqBUOfiAFxrlD3IVAfB4xDWGilsNwiX4tvSCNmi4ajzO00TQyGJ6xF3QXt71uoQ1HpHNFWllbcS16RU1ZTKV2di3h8okq+JYey273VTbUeCPqG5icl+NErKx0Bxvmyo13FB+0mk2tPFUTlgRoykmFLDrGqhP7lP99m2Duha+r4SRJ9VdNjq0Jb+4u9B0z4K2LFueiqwJsVvSBJzUfBpIM28TOXAsU2RflKscRB8LNdLvndo0TBGA+xREmLZbmtqeZ3YJ6lR3gfKTJlp7tTKI6735fPaNEkJqoY2LM57YYSDoubPBRHwMdyC9gZ2E729bHHxrwu5aVq9ouDTTh4T6HzXgr6p5RVDEo+YAjgjaGB5aH1fRKOXNwBi+ItRz/QKTDWPTi3kNjKgNChhO7M4x1hweW1CvsFwEHebeo/i1JasznjX2UGhFrr5zIbCIanX7+9+Sy79W/W+K1O2P0ip2WJO8lpH+HwSiUjKPFq5a2LJJR27r+JrfRfeERhj0ElDnAX2WrzQbBKD3eyh+ddp435AwCW5wjbls0UhqBvysU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
