travis:
  secure:
    BINSTAR_TOKEN: CA3o5MMo3arlhr5kwtXyELdaQwO4w1syU34S4fPfX72rBeMse+6rfcyq1XlCv79HZwKx7dgWuf9aYWo8nmYZHOIG3XAdjR1UvDXO9Qy0JHcaR3Pp3eLGowGhqGG5abGIPqx2xttONxX9t7kbRPxkMde8sTGjZ/np0tozgJMrUJNbz3UnWjUxhUnRUbEwkbJvtMPZsl7O9UX8g3VT8VAa7D2IE3TEdz3+gAWXz0Gn1w82pKEdWIXi7sGmjsm2RnJ1RVKcdfJgYdxEKHrDghK04U17v1ja+kk7UIVMJQ8rE1s6LSzjOmtDXXy65bZdnpQgcIaxlrTwqGsPF/LvILp8jp8ed8xQI3WxFh9NoVfZry+8Wanzn1rDbmSABlbFCjbaUphY7g3TCbeK0U8aCv8KWuaL7fZPu4aAQ42Hg+8CxVqGxwTd8mcETSgpPRYTFK5xG37HESPUABfuKF6/FS7T/YRL9l4tqiiYqGj8VdIL/tGOpBuC5/S3dr5IFLp83IDPeGzPQjEaNxfzwNReBoxQknkyedNEp5eRqK37dHiA5kkQ1qPwSz1prrj1VjZox8cI6AUZtMs9iixL8oNfLngGWjmOA9lKq/1JvJ45rUYhz7Ry/dhaJe9+nmVZwN3rO+qWovpjMt2qNkMnaSYYY8cIbi5SutaNqORfUcATK4yE8EE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
