travis:
  secure:
    BINSTAR_TOKEN: qsngNkTrMpzhGKzx7yGmptqym8C8btYqoRf8C96rabjy7CsA8AeUXPhjmWxUKwa+TxaozjIiE0zuRcKFsKn96aClYtPnOFzLhXEj3C7CpQTm7peAoyECq1yKdkXVZrCQEiVd4OsKaPdJsarGh/Wymj6wq8jVK3u1pgnsQ6XipjbiTXCopqK5R+CX81JQxkW7rn0Q/uIg2WT/ZZo1eC98nTpe3Io/mQ4nEtGv4iviXpm8b/NFJJ3Q6cgN1mgkBze9ef/cIYLLUKu24bUn/SDjjDTKn7tCApJVTfveJPTY9x769Cgh9CMmIJ5/JJcT0BXdYFdPI6gn0VG5MIUm2AnqUS7X4IVdnjA0bTuVniMgm60fEemYPX8FSs5icXjGLOAXhEbVC5hs6tVbEV51eLGDio5+WkmVHGWLIENOJT7+/QNfuZGHxOxVr5RgVhoTZaKUBcysANe/ZXex+yflnyANSgQstkV+JjQfmut4u0qDxdq/1PnfuhS9FDkgaTqef1VEV/JXDlyWO11OPSwaz/pTD+auIaShWcVjlJoUrQ+NACxNECY2dJWbv0KV8UO6e/quKs+YBEIQ582VKypSrcURzvdsgWpjJDjKxki9VmqgW5TdSx3wd3b9xTfDoa86ZqdP4JmGlmlQhNVXKBgy4MieuV7d+9/0sfSPZjtwmHreEm8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
